'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import type { AdminRole } from '@/lib/admin-auth'
import type { TrainingModule, TrainingProgram } from '@/lib/training'

const api = '/api/admin/training'
const makeId = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
type Form = { title: string; description: string; status: 'draft' | 'published'; audience_roles: string[]; assigned_emails: string; modules: TrainingModule[] }
const blank: Form = { title: '', description: '', status: 'draft', audience_roles: ['clinical'], assigned_emails: '', modules: [] }

function programForm(program: TrainingProgram): Form {
  return { title: program.title, description: program.description, status: program.status, audience_roles: program.audience_roles, assigned_emails: program.assigned_emails.join('\n'), modules: program.modules }
}

export default function Training({ role }: { role: AdminRole }) {
  const [programs, setPrograms] = useState<TrainingProgram[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const [editing, setEditing] = useState<TrainingProgram | 'new' | null>(null); const [open, setOpen] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(''); const response = await fetch(api); const result = await response.json().catch(() => ({})); response.ok ? setPrograms(result.programs || []) : setError(result.error || 'Could not load training.'); setLoading(false) }, [])
  useEffect(() => { load() }, [load])

  async function save(form: Form, id?: string) {
    const response = await fetch(api, { method: id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, assigned_emails: form.assigned_emails.split(/[\n,]+/).map((email) => email.trim()).filter(Boolean), ...(id ? { id } : {}) }) })
    const result = await response.json().catch(() => ({})); if (!response.ok) { setError(result.error || 'Could not save training.'); return false } await load(); return true
  }
  async function remove(program: TrainingProgram) { if (!confirm(`Permanently delete “${program.title}”?`)) return; const response = await fetch(`${api}?id=${program.id}`, { method: 'DELETE' }); if (response.ok) await load(); else setError((await response.json()).error || 'Could not delete training.') }
  async function complete(program: TrainingProgram, lessonId: string, completed: boolean) {
    const response = await fetch(api, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: program.id, lessonId, completed }) }); const result = await response.json().catch(() => ({}))
    if (!response.ok) return setError(result.error || 'Could not update progress.')
    setPrograms((items) => items.map((item) => item.id === program.id ? { ...item, ...result } : item))
  }
  if (loading) return <div className="rounded-2xl border bg-white p-16 text-center text-text-mid">Loading training…</div>
  return <div className="space-y-6">
    {error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {role === 'admin' ? <AdminPrograms programs={programs} onEdit={setEditing} onDelete={remove} /> : <LearnerPrograms programs={programs} open={open} setOpen={setOpen} onComplete={complete} />}
    {editing && <Editor program={editing === 'new' ? null : editing} onClose={() => setEditing(null)} onSave={async (form) => { const ok = await save(form, editing === 'new' ? undefined : editing.id); if (ok) setEditing(null); return ok }} />}
  </div>
}

function AdminPrograms({ programs, onEdit, onDelete }: { programs: TrainingProgram[]; onEdit: (value: TrainingProgram | 'new') => void; onDelete: (program: TrainingProgram) => void }) {
  const published = programs.filter((p) => p.status === 'published').length
  return <><div className="grid gap-4 sm:grid-cols-3"><Stat label="Programs" value={programs.length} /><Stat label="Published" value={published} /><Stat label="Drafts" value={programs.length - published} /></div>
    <section className="overflow-hidden rounded-[20px] border border-green-deep/10 bg-white shadow-lg"><div className="flex flex-wrap items-center justify-between gap-4 border-b p-6"><div><h3 className="text-2xl font-bold text-green-deep">Training programs</h3><p className="mt-1 text-sm text-text-mid">Build lessons, choose role audiences, or assign individual members by email.</p></div><button onClick={() => onEdit('new')} className="rounded-full bg-green-deep px-5 py-2.5 text-sm font-bold text-white">+ New program</button></div>
      {!programs.length ? <p className="p-16 text-center text-text-mid">No programs yet. Create the first staff training program.</p> : <div className="divide-y">{programs.map((program) => { const lessons = program.modules.reduce((n, m) => n + m.lessons.length, 0); return <div key={program.id} className="flex flex-wrap items-start justify-between gap-4 p-6"><div className="min-w-[240px] flex-1"><div className="flex items-center gap-2"><h4 className="text-lg font-bold text-green-deep">{program.title}</h4><Badge>{program.status}</Badge></div><p className="mt-1 text-sm text-text-mid">{program.description || 'No description'}</p><p className="mt-2 text-xs text-gray-500">{program.modules.length} modules · {lessons} lessons · {program.audience_roles.join(', ') || 'Individual'}{program.assigned_emails.length ? ` · ${program.assigned_emails.length} direct assignment(s)` : ''}</p></div><div className="flex gap-2"><button onClick={() => onEdit(program)} className="rounded-full border px-4 py-2 text-xs font-bold text-green-deep">Edit</button><button onClick={() => onDelete(program)} className="rounded-full px-3 py-2 text-xs font-bold text-red-600">Delete</button></div></div>})}</div>}
    </section></>
}

function LearnerPrograms({ programs, open, setOpen, onComplete }: { programs: TrainingProgram[]; open: string | null; setOpen: (id: string | null) => void; onComplete: (p: TrainingProgram, id: string, done: boolean) => void }) {
  if (!programs.length) return <div className="rounded-[20px] border bg-white p-16 text-center"><h3 className="text-xl font-bold text-green-deep">No training assigned</h3><p className="mt-2 text-text-mid">New programs for your role will appear here.</p></div>
  return <div className="grid gap-5">{programs.map((program) => <section key={program.id} className="overflow-hidden rounded-[20px] border border-green-deep/10 bg-white shadow-sm"><button onClick={() => setOpen(open === program.id ? null : program.id)} className="w-full p-6 text-left"><div className="flex items-start justify-between gap-5"><div><Badge>{program.progress_percent === 100 ? 'complete' : 'assigned'}</Badge><h3 className="mt-3 text-2xl font-bold text-green-deep">{program.title}</h3><p className="mt-1 text-sm leading-6 text-text-mid">{program.description}</p></div><span className="text-2xl text-green-deep">{open === program.id ? '−' : '+'}</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-gold" style={{ width: `${program.progress_percent || 0}%` }} /></div><p className="mt-2 text-xs font-bold text-green-mid">{program.progress_percent || 0}% complete</p></button>
    {open === program.id && <div className="border-t bg-[#fbfaf6] p-6">{program.modules.map((module, index) => <div key={module.id} className="mb-6 last:mb-0"><h4 className="font-bold text-green-deep">Module {index + 1}: {module.title}</h4><div className="mt-3 space-y-3">{module.lessons.map((lesson) => { const done = program.completed_lesson_ids?.includes(lesson.id) || false; return <article key={lesson.id} className="rounded-xl border bg-white p-4"><div className="flex gap-3"><input aria-label={`Mark ${lesson.title} complete`} type="checkbox" checked={done} onChange={(e) => onComplete(program, lesson.id, e.target.checked)} className="mt-1 h-4 w-4 accent-green-deep" /><div><h5 className="font-bold text-green-deep">{lesson.title} {lesson.durationMinutes ? <span className="font-normal text-gray-400">· {lesson.durationMinutes} min</span> : null}</h5><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-text-mid">{lesson.content}</p>{lesson.resourceUrl && <a href={lesson.resourceUrl} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-sm font-bold text-green-mid underline">Open lesson resource ↗</a>}</div></div></article>})}</div></div>)}</div>}
  </section>)}</div>
}

function Editor({ program, onClose, onSave }: { program: TrainingProgram | null; onClose: () => void; onSave: (form: Form) => Promise<boolean> }) {
  const [form, setForm] = useState<Form>(program ? programForm(program) : blank); const [saving, setSaving] = useState(false)
  const lessonCount = useMemo(() => form.modules.reduce((n, m) => n + m.lessons.length, 0), [form.modules])
  const updateModule = (index: number, module: TrainingModule) => setForm((f) => ({ ...f, modules: f.modules.map((m, i) => i === index ? module : m) }))
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose() }}><div role="dialog" aria-modal="true" className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-7 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-green-mid">Training builder</p><h3 className="mt-1 text-2xl font-bold text-green-deep">{program ? 'Edit program' : 'New program'}</h3></div><button onClick={onClose} className="h-9 w-9 rounded-full bg-gray-100 text-xl">×</button></div>
    <form onSubmit={async (e) => { e.preventDefault(); setSaving(true); await onSave(form); setSaving(false) }} className="mt-6 space-y-5"><Field label="Program title"><input required maxLength={160} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="input" /></Field><Field label="Description"><textarea rows={3} maxLength={3000} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="input" /></Field>
      <div className="grid gap-5 sm:grid-cols-2"><Field label="Audience roles"><div className="mt-2 flex gap-5">{['clinical', 'sales'].map((role) => <label key={role} className="flex items-center gap-2 font-normal capitalize"><input type="checkbox" checked={form.audience_roles.includes(role)} onChange={(e) => setForm({ ...form, audience_roles: e.target.checked ? [...form.audience_roles, role] : form.audience_roles.filter((r) => r !== role) })} />{role}</label>)}</div></Field><Field label="Status"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as Form['status'] })} className="input"><option value="draft">Draft</option><option value="published">Published</option></select></Field></div>
      <Field label="Specific member emails" hint="Optional; one per line or comma-separated"><textarea rows={3} value={form.assigned_emails} onChange={(e) => setForm({ ...form, assigned_emails: e.target.value })} placeholder="member@fxmed.ng" className="input" /></Field>
      <div className="rounded-2xl border bg-[#fbfaf6] p-5"><div className="flex items-center justify-between"><div><h4 className="font-bold text-green-deep">Course content</h4><p className="text-xs text-text-mid">{form.modules.length} modules · {lessonCount} lessons</p></div><button type="button" onClick={() => setForm({ ...form, modules: [...form.modules, { id: makeId('module'), title: '', lessons: [] }] })} className="rounded-full bg-green-deep px-4 py-2 text-xs font-bold text-white">+ Module</button></div>
        <div className="mt-4 space-y-4">{form.modules.map((module, mi) => <div key={module.id} className="rounded-xl border bg-white p-4"><div className="flex gap-2"><input required value={module.title} onChange={(e) => updateModule(mi, { ...module, title: e.target.value })} placeholder={`Module ${mi + 1} title`} className="input mt-0" /><button type="button" onClick={() => setForm({ ...form, modules: form.modules.filter((_, i) => i !== mi) })} className="px-2 text-red-600">×</button></div><div className="mt-4 space-y-3">{module.lessons.map((lesson, li) => <div key={lesson.id} className="rounded-xl bg-gray-50 p-4"><div className="flex gap-2"><input required value={lesson.title} onChange={(e) => updateModule(mi, { ...module, lessons: module.lessons.map((l, i) => i === li ? { ...l, title: e.target.value } : l) })} placeholder="Lesson title" className="input mt-0" /><button type="button" onClick={() => updateModule(mi, { ...module, lessons: module.lessons.filter((_, i) => i !== li) })} className="px-2 text-red-600">×</button></div><textarea rows={4} value={lesson.content} onChange={(e) => updateModule(mi, { ...module, lessons: module.lessons.map((l, i) => i === li ? { ...l, content: e.target.value } : l) })} placeholder="Lesson content" className="input" /><div className="grid gap-3 sm:grid-cols-[1fr_150px]"><input type="url" value={lesson.resourceUrl} onChange={(e) => updateModule(mi, { ...module, lessons: module.lessons.map((l, i) => i === li ? { ...l, resourceUrl: e.target.value } : l) })} placeholder="Resource or video URL (optional)" className="input" /><input type="number" min="0" value={lesson.durationMinutes} onChange={(e) => updateModule(mi, { ...module, lessons: module.lessons.map((l, i) => i === li ? { ...l, durationMinutes: Number(e.target.value) } : l) })} placeholder="Minutes" className="input" /></div></div>)}</div><button type="button" onClick={() => updateModule(mi, { ...module, lessons: [...module.lessons, { id: makeId('lesson'), title: '', content: '', resourceUrl: '', durationMinutes: 0 }] })} className="mt-3 text-xs font-bold text-green-mid">+ Add lesson</button></div>)}</div>
      </div><div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-full border px-5 py-3 text-sm font-bold">Cancel</button><button disabled={saving} className="rounded-full bg-green-deep px-6 py-3 text-sm font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : program ? 'Save changes' : 'Create program'}</button></div></form></div></div>
}

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <label className="block text-sm font-bold text-green-deep">{label} {hint && <span className="font-normal text-gray-400">— {hint}</span>}{children}</label> }
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-[18px] border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-green-mid">{label}</p><p className="mt-2 text-3xl font-bold text-green-deep">{value}</p></div> }
function Badge({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-green-50 px-3 py-1 text-[10px] font-bold uppercase tracking-wide text-green-700">{children}</span> }
